GW.define('Tool.REGISTER', 'tool', {
	order: 100,
	name: 'register',
	description: 'Register new mega.co.nz account',
	usages: [
               '--ephemeral [--password <password> | --password-file <path>]',
               '--email <email> --name <realname> [--password <password> | --password-file <path>]',
               '--confirm --signup-link <signuplink> [--password <password> | --password-file <path>]'
	],

	detail: [
		'You can register either full user account linked to some e-mail address, or temporary ephemeral account linked to user handle that will be generated by the server.',
		'Full account registration requires you to retrieve confirmation link from the MEGA Signup email, that will be sent to the provided e-mail address.',
		'This command is interactive, and you\'ll be asked to enter password and the signup confirmation link when necessary.',
		'No strength checking is done, so make sure you pick a strong password yourself.'
	],

	getOptsSpecCustom: function() {
		return [{
			longName: "email",
			arg: 'string',
			help: "Email serves as your new account username, that you'll be using to sign in.",
			argHelp: "EMAIL" 
		}, {
			longName: "name",
			arg: 'string',
			help: "Your real (or fake) name. Default is 'User'",
			argHelp: "REALNAME"    
		}, {
			longName: "confirm",
			help: 'Confirm account previously created by `megatools register`.'
		}, {
			longName: 'signup-link',
			arg: 'string',
			argHelp: 'SIGNUPLINK',
			help: 'You need to pass signup link from the confirmation email that was sent to `<email>`.'
		}, {
			longName: "ephemeral",
			help: "Create new ephemeral account. Ephemeral accounts may be removed at any time without prior notice, but they don't require e-mail confirmation."
		}, {
			longName: "password",
			shortName: 'p',
			arg: 'string',
			help: "Desired password. This option is less secure than the --password-file option.",
			argHelp: "PASSWORD"
		}, {
			longName: "password-file",
			arg: 'string',
			help: "Path to a file containing the desired password. All characters including leading and trailing spaces up to the first new line are used.",
			argHelp: "PATH"
		}, {
			longName: 'save-config',
			shortName: 's',
			help: 'Save login credentials to a configuration file specified by --config.'
		}, {
			longName: 'config',
			arg: 'string',
			argHelp: 'PATH',
			help: 'Configuration file path. Default is ' + MEGA_RC_FILENAME + ' in the current directory.'
		}];
	},

	examples: [{
		title: 'Simple interactive registration',
		commands: [
			'$ megatools register --save-config --email your@email.com --name "Your Name"',
			'$ megatools info'
		]
	}, {
		title: 'Batch registration',
		steps: [{
			description: 'First create a non-verified account:',
			commands: [
				'$ megareg --batch --email your@email.com --name "Your Name" --password "Your Password"'
			]
		}, {
			description: 'Now wait for a verification mail and run the command as asked:',
			commands: [
				'$ megareg --batch --confirm --signup-link @LINK@ --password "Your Password"'
			]
		}]
	}],

	run: function() {
		// check options
		var me = this;
		var opts = me.opts;
		var password, handle, signupCode;
		var api = new MegaAPI();

		var usedCommands = _([opts.email, opts.confirm, opts.ephemeral]).compact().length;
		if (usedCommands > 1) {
			return Defer.rejected('args', 'You can\'t combine --email, --confirm or --ephemeral options');
		}

		if (usedCommands == 0) {
			return Defer.rejected('nop', 'Nothing to do!');
		}

		if (opts.email && !C.email_valid(opts.email)) {
			return Defer.rejected('args', 'Invalid email address ' + opts.email + '!');
		}

		if (opts.confirm) {
			if (opts['signup-link']) {
				signupCode = extractSignupCode(opts['signup-link']);
				if (!signupCode) {
					return Defer.rejected('args', 'Invalid signup link!');
				}
			} else {
				if (opts.batch) {
					return Defer.rejected('args', 'You need to provide signup link on the command line in batch mode.');
				}
			}
		}

		function extractSignupCode(v) {
			var m = String(v).match(/https:\/\/mega\.co\.nz\/#confirm([A-Za-z0-9_-]{80,150})/);
			if (m) {
				return m[1];
			}
		}

		function doRegister() {
			return api.registerUser(opts.name || 'User', opts.email, password).done(function(res) {
				if (opts.batch) {
					return Defer.resolved();
				}

				return me.promptCode('Check email account ' + opts.email + ' and enter signup link (or type abort): ', extractSignupCode).done(function(code) {
					return api.confirmUserFast(code, res.mk, res.pk, res.email);
				});
			}).done(function() {
				Log.verbose('Registration was successful!');
				saveConfig();
			});
		}

		function confirmUser(code) {
			return api.confirmUser(code, password).done(function(res) {
				handle = res.email;
				saveConfig();
			});
		}

		function doConfirm() {
			if (signupCode) {
				return confirmUser(signupCode);
			}

			return me.promptCode('Enter signup link (or type abort): ', extractSignupCode).done(function(code) {
				return confirmUser(code);
			});
		}

		function doEphemeral() {
			return api.registerEphemeral(password).done(function(res) {
				handle = res.uh;
				saveConfig();

				if (opts.batch) {
					Log.msg(handle);
				} else {
					Log.msg('Create ephemeral account: ' + handle);
				}
			});
		}

		function saveConfig() {
			me.saveCredentials(opts.email || handle, password);
		}

		return this.acquirePasswordFromOptFileOrUser('password', true).done(function(pw) {
			password = pw;

			if (opts.email) {
				return doRegister();
			} else if (opts.confirm) {
				return doConfirm();
			} else if (opts.ephemeral) {
				return doEphemeral();
			}

			return Defer.rejected('noreach', 'Should not happen');
		});
	}
});
