/* Generated by re2c 0.13.5 on Thu Feb  6 16:16:24 2014 */
#line 1 "sjson.c"
/**
 * sjson - fast string based JSON parser/generator library
 * Copyright (C) 2013  Ondřej Jirman <megous@megous.com>
 *
 * WWW: https://github.com/megous/sjson
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <string.h>
#include <stdio.h>
#include "sjson.h"

enum
{
  TOK_NONE = 0, // no more tokens
  TOK_OBJ_START,
  TOK_OBJ_END,
  TOK_ARRAY_START,
  TOK_ARRAY_END,
  TOK_COLON,
  TOK_COMMA,
  TOK_STRING,
  TOK_NOESC_STRING,
  TOK_NUMBER,
  TOK_FALSE,
  TOK_TRUE,
  TOK_NULL,
  TOK_INVALID
};

#line 67 "sjson.c"


static gint s_json_get_token(const gchar* json, const gchar** start, const gchar** end)
{
  g_return_val_if_fail(json != NULL, FALSE);

  const guchar* c = (const guchar*)json;
  const guchar* m = NULL;
  const guchar* s;
  gint token;

  while (TRUE)
  {
    s = c;


#line 63 "sjson.gen.c"
	{
		guchar yych;
		unsigned int yyaccept = 0;

		yych = (guchar)*c;
		if (yych <= '9') {
			if (yych <= ' ') {
				if (yych <= '\n') {
					if (yych <= 0x00) goto yy25;
					if (yych <= 0x08) goto yy27;
				} else {
					if (yych == '\r') goto yy2;
					if (yych <= 0x1F) goto yy27;
				}
			} else {
				if (yych <= ',') {
					if (yych == '"') goto yy12;
					if (yych <= '+') goto yy27;
					goto yy16;
				} else {
					if (yych <= '-') goto yy18;
					if (yych <= '/') goto yy27;
					if (yych <= '0') goto yy19;
					goto yy21;
				}
			}
		} else {
			if (yych <= 'm') {
				if (yych <= '\\') {
					if (yych <= ':') goto yy14;
					if (yych == '[') goto yy8;
					goto yy27;
				} else {
					if (yych <= ']') goto yy10;
					if (yych == 'f') goto yy23;
					goto yy27;
				}
			} else {
				if (yych <= 'z') {
					if (yych <= 'n') goto yy24;
					if (yych == 't') goto yy22;
					goto yy27;
				} else {
					if (yych <= '{') goto yy4;
					if (yych == '}') goto yy6;
					goto yy27;
				}
			}
		}
yy2:
		++c;
		yych = (guchar)*c;
		goto yy66;
yy3:
#line 83 "sjson.c"
		{ 
      continue; 
    }
#line 122 "sjson.gen.c"
yy4:
		++c;
#line 87 "sjson.c"
		{
      token = TOK_OBJ_START;
      goto done;
    }
#line 130 "sjson.gen.c"
yy6:
		++c;
#line 92 "sjson.c"
		{
      token = TOK_OBJ_END;
      goto done;
    }
#line 138 "sjson.gen.c"
yy8:
		++c;
#line 97 "sjson.c"
		{
      token = TOK_ARRAY_START;
      goto done;
    }
#line 146 "sjson.gen.c"
yy10:
		++c;
#line 102 "sjson.c"
		{
      token = TOK_ARRAY_END;
      goto done;
    }
#line 154 "sjson.gen.c"
yy12:
		yyaccept = 0;
		yych = (guchar)*(m = ++c);
		if (yych >= 0x01) goto yy53;
yy13:
#line 151 "sjson.c"
		{
      return TOK_INVALID;
    }
#line 164 "sjson.gen.c"
yy14:
		++c;
#line 117 "sjson.c"
		{
      token = TOK_COLON;
      goto done;
    }
#line 172 "sjson.gen.c"
yy16:
		++c;
#line 122 "sjson.c"
		{
      token = TOK_COMMA;
      goto done;
    }
#line 180 "sjson.gen.c"
yy18:
		yych = (guchar)*++c;
		if (yych <= '/') goto yy13;
		if (yych <= '0') goto yy51;
		if (yych <= '9') goto yy42;
		goto yy13;
yy19:
		yyaccept = 1;
		yych = (guchar)*(m = ++c);
		if (yych <= 'D') {
			if (yych == '.') goto yy44;
		} else {
			if (yych <= 'E') goto yy45;
			if (yych == 'e') goto yy45;
		}
yy20:
#line 127 "sjson.c"
		{
      token = TOK_NUMBER;
      goto done;
    }
#line 202 "sjson.gen.c"
yy21:
		yyaccept = 1;
		yych = (guchar)*(m = ++c);
		goto yy43;
yy22:
		yyaccept = 0;
		yych = (guchar)*(m = ++c);
		if (yych == 'r') goto yy38;
		goto yy13;
yy23:
		yyaccept = 0;
		yych = (guchar)*(m = ++c);
		if (yych == 'a') goto yy33;
		goto yy13;
yy24:
		yyaccept = 0;
		yych = (guchar)*(m = ++c);
		if (yych == 'u') goto yy28;
		goto yy13;
yy25:
		++c;
#line 147 "sjson.c"
		{ 
      return TOK_NONE;
    }
#line 228 "sjson.gen.c"
yy27:
		yych = (guchar)*++c;
		goto yy13;
yy28:
		yych = (guchar)*++c;
		if (yych == 'l') goto yy30;
yy29:
		c = m;
		if (yyaccept <= 0) {
			goto yy13;
		} else {
			goto yy20;
		}
yy30:
		yych = (guchar)*++c;
		if (yych != 'l') goto yy29;
		++c;
#line 142 "sjson.c"
		{
      token = TOK_NULL;
      goto done;
    }
#line 251 "sjson.gen.c"
yy33:
		yych = (guchar)*++c;
		if (yych != 'l') goto yy29;
		yych = (guchar)*++c;
		if (yych != 's') goto yy29;
		yych = (guchar)*++c;
		if (yych != 'e') goto yy29;
		++c;
#line 137 "sjson.c"
		{
      token = TOK_FALSE;
      goto done;
    }
#line 265 "sjson.gen.c"
yy38:
		yych = (guchar)*++c;
		if (yych != 'u') goto yy29;
		yych = (guchar)*++c;
		if (yych != 'e') goto yy29;
		++c;
#line 132 "sjson.c"
		{
      token = TOK_TRUE;
      goto done;
    }
#line 277 "sjson.gen.c"
yy42:
		yyaccept = 1;
		m = ++c;
		yych = (guchar)*c;
yy43:
		if (yych <= '9') {
			if (yych == '.') goto yy44;
			if (yych <= '/') goto yy20;
			goto yy42;
		} else {
			if (yych <= 'E') {
				if (yych <= 'D') goto yy20;
				goto yy45;
			} else {
				if (yych == 'e') goto yy45;
				goto yy20;
			}
		}
yy44:
		yych = (guchar)*++c;
		if (yych <= '/') goto yy29;
		if (yych <= '9') goto yy49;
		goto yy29;
yy45:
		yych = (guchar)*++c;
		if (yych <= ',') {
			if (yych != '+') goto yy29;
		} else {
			if (yych <= '-') goto yy46;
			if (yych <= '/') goto yy29;
			if (yych <= '9') goto yy47;
			goto yy29;
		}
yy46:
		yych = (guchar)*++c;
		if (yych <= '/') goto yy29;
		if (yych >= ':') goto yy29;
yy47:
		++c;
		yych = (guchar)*c;
		if (yych <= '/') goto yy20;
		if (yych <= '9') goto yy47;
		goto yy20;
yy49:
		yyaccept = 1;
		m = ++c;
		yych = (guchar)*c;
		if (yych <= 'D') {
			if (yych <= '/') goto yy20;
			if (yych <= '9') goto yy49;
			goto yy20;
		} else {
			if (yych <= 'E') goto yy45;
			if (yych == 'e') goto yy45;
			goto yy20;
		}
yy51:
		yyaccept = 1;
		yych = (guchar)*(m = ++c);
		if (yych <= 'D') {
			if (yych == '.') goto yy44;
			goto yy20;
		} else {
			if (yych <= 'E') goto yy45;
			if (yych == 'e') goto yy45;
			goto yy20;
		}
yy52:
		++c;
		yych = (guchar)*c;
yy53:
		if (yych <= '"') {
			if (yych <= 0x00) goto yy29;
			if (yych <= '!') goto yy52;
			goto yy55;
		} else {
			if (yych != '\\') goto yy52;
		}
yy54:
		++c;
		yych = (guchar)*c;
		if (yych <= 'e') {
			if (yych <= '/') {
				if (yych == '"') goto yy58;
				if (yych <= '.') goto yy29;
				goto yy58;
			} else {
				if (yych <= '\\') {
					if (yych <= '[') goto yy29;
					goto yy58;
				} else {
					if (yych == 'b') goto yy58;
					goto yy29;
				}
			}
		} else {
			if (yych <= 'q') {
				if (yych <= 'f') goto yy58;
				if (yych == 'n') goto yy58;
				goto yy29;
			} else {
				if (yych <= 's') {
					if (yych <= 'r') goto yy58;
					goto yy29;
				} else {
					if (yych <= 't') goto yy58;
					if (yych <= 'u') goto yy57;
					goto yy29;
				}
			}
		}
yy55:
		++c;
#line 107 "sjson.c"
		{
      token = TOK_NOESC_STRING;
      goto done;
    }
#line 396 "sjson.gen.c"
yy57:
		++c;
		yych = (guchar)*c;
		if (yych <= '@') {
			if (yych <= '/') goto yy29;
			if (yych <= '9') goto yy62;
			goto yy29;
		} else {
			if (yych <= 'F') goto yy62;
			if (yych <= '`') goto yy29;
			if (yych <= 'f') goto yy62;
			goto yy29;
		}
yy58:
		++c;
		yych = (guchar)*c;
		if (yych <= '"') {
			if (yych <= 0x00) goto yy29;
			if (yych <= '!') goto yy58;
		} else {
			if (yych == '\\') goto yy54;
			goto yy58;
		}
		++c;
#line 112 "sjson.c"
		{
      token = TOK_STRING;
      goto done;
    }
#line 426 "sjson.gen.c"
yy62:
		++c;
		yych = (guchar)*c;
		if (yych <= '@') {
			if (yych <= '/') goto yy29;
			if (yych >= ':') goto yy29;
		} else {
			if (yych <= 'F') goto yy63;
			if (yych <= '`') goto yy29;
			if (yych >= 'g') goto yy29;
		}
yy63:
		++c;
		yych = (guchar)*c;
		if (yych <= '@') {
			if (yych <= '/') goto yy29;
			if (yych >= ':') goto yy29;
		} else {
			if (yych <= 'F') goto yy64;
			if (yych <= '`') goto yy29;
			if (yych >= 'g') goto yy29;
		}
yy64:
		++c;
		yych = (guchar)*c;
		if (yych <= '@') {
			if (yych <= '/') goto yy29;
			if (yych <= '9') goto yy58;
			goto yy29;
		} else {
			if (yych <= 'F') goto yy58;
			if (yych <= '`') goto yy29;
			if (yych <= 'f') goto yy58;
			goto yy29;
		}
yy65:
		++c;
		yych = (guchar)*c;
yy66:
		if (yych <= '\f') {
			if (yych <= 0x08) goto yy3;
			if (yych <= '\n') goto yy65;
			goto yy3;
		} else {
			if (yych <= '\r') goto yy65;
			if (yych == ' ') goto yy65;
			goto yy3;
		}
	}
#line 154 "sjson.c"

  }

done:
  if (start)
    *start = s;
  if (end)
    *end = c;
  return token;
}

static SJsonType token_to_type(gint token)
{
  switch (token)
  {
    case TOK_NONE        : return S_JSON_TYPE_NONE;
    case TOK_OBJ_START   : return S_JSON_TYPE_OBJECT;
    case TOK_ARRAY_START : return S_JSON_TYPE_ARRAY;
    case TOK_STRING      : return S_JSON_TYPE_STRING;
    case TOK_NOESC_STRING: return S_JSON_TYPE_STRING;
    case TOK_NUMBER      : return S_JSON_TYPE_NUMBER;
    case TOK_FALSE       : return S_JSON_TYPE_BOOL;
    case TOK_TRUE        : return S_JSON_TYPE_BOOL;
    case TOK_NULL        : return S_JSON_TYPE_NULL;
    default              : return S_JSON_TYPE_INVALID;
  }
}

// public api

static gboolean s_json_is_valid_inner(const gchar* json, const gchar** end)
{
  const gchar* next;
  gint token;

  g_return_val_if_fail(json != NULL, FALSE);
  
  token = s_json_get_token(json, NULL, &next);
  if (token == TOK_ARRAY_START)
  {
    const gchar* array_elem = next;
    const gchar* array_next = NULL;
    gboolean expect_comma = FALSE;

    while (TRUE)
    {
      // check end of array
      token = s_json_get_token(array_elem, NULL, &array_next);
      if (token == TOK_ARRAY_END)
      {
        if (end)
          *end = array_next;
        return TRUE;
      }

      if (expect_comma)
      {
        if (token == TOK_COMMA)
          array_elem = array_next; // skip comma
        else
          return FALSE;
      }

      // check element
      if (!s_json_is_valid_inner(array_elem, &array_elem))
        return FALSE;

      expect_comma = TRUE;
    }
  }
  else if (token == TOK_OBJ_START)
  {
    const gchar* obj_next = next;
    gboolean expect_comma = FALSE;

    while (TRUE)
    {
      // check end of object
      token = s_json_get_token(obj_next, NULL, &obj_next);
      if (token == TOK_OBJ_END)
      {
        if (end)
          *end = obj_next;

        return TRUE;
      }

      // eat comma
      if (expect_comma)
      {
        if (token != TOK_COMMA)
          return FALSE;

        token = s_json_get_token(obj_next, NULL, &obj_next);
      }

      // check member name and colon
      if (token != TOK_STRING && token != TOK_NOESC_STRING)
        return FALSE;

      token = s_json_get_token(obj_next, NULL, &obj_next);
      if (token != TOK_COLON)
        return FALSE;

      // check member value
      if (!s_json_is_valid_inner(obj_next, &obj_next))
        return FALSE;

      expect_comma = TRUE;
    }
  }
  else if (token == TOK_STRING || token == TOK_NOESC_STRING || token == TOK_NUMBER || token == TOK_FALSE || token == TOK_TRUE || token == TOK_NULL)
  {
    if (end)
      *end = next;
    return TRUE;
  }

  return FALSE;
}

gboolean s_json_is_valid(const gchar* json)
{
  const gchar* next;

  g_return_val_if_fail(json != NULL, FALSE);
  
  return s_json_is_valid_inner(json, &next) && s_json_get_token(next, NULL, NULL) == TOK_NONE;
}

gchar* s_json_get(const gchar* json)
{
  const gchar* next;
  const gchar* start = NULL;

  g_return_val_if_fail(json != NULL, NULL);
  
  if (s_json_is_valid_inner(json, &next))
  {
    s_json_get_token(json, &start, NULL); // must set start

    return g_strndup(start, next - start);
  }

  return NULL;
}

SJsonType s_json_get_type(const gchar* json)
{
  g_return_val_if_fail(json != NULL, S_JSON_TYPE_INVALID);

  return token_to_type(s_json_get_token(json, NULL, NULL));
}

const gchar* s_json_get_element_first(const gchar* json)
{
  const gchar* next_elem;
  gint token;

  g_return_val_if_fail(json != NULL, NULL);

  token = s_json_get_token(json, NULL, &next_elem);
  if (token != TOK_ARRAY_START)
    return NULL;

  if (s_json_get_token(next_elem, NULL, NULL) == TOK_ARRAY_END)
    return NULL;

  return next_elem;
}

const gchar* s_json_get_element_next(const gchar* iter)
{
  const gchar* next_elem;
  gint token;

  g_return_val_if_fail(iter != NULL, NULL);

  if (!s_json_is_valid_inner(iter, &next_elem))
    return NULL;

  token = s_json_get_token(next_elem, NULL, &next_elem);
  if (token != TOK_COMMA)
    return NULL;

  return next_elem;
}

const gchar* s_json_get_element(const gchar* json, guint index)
{
  guint current_index = 0;

  g_return_val_if_fail(json != NULL, NULL);

  S_JSON_FOREACH_ELEMENT(json, elem)

    if (current_index == index)
      return elem;

    current_index++;

  S_JSON_FOREACH_END()

  return NULL;
}

gchar** s_json_get_elements(const gchar* json)
{
  GPtrArray* arr;

  g_return_val_if_fail(json != NULL, NULL);

  arr = g_ptr_array_sized_new(64);

  S_JSON_FOREACH_ELEMENT(json, elem)
    g_ptr_array_add(arr, (gchar*)elem);
  S_JSON_FOREACH_END()

  g_ptr_array_add(arr, NULL);

  return (gchar**)g_ptr_array_free(arr, FALSE);
}

gsize s_json_get_element_count(const gchar* json)
{
  gsize count = 0;

  g_return_val_if_fail(json != NULL, NULL);

  S_JSON_FOREACH_ELEMENT(json, elem)
    count++;
  S_JSON_FOREACH_END()

  return count;
}

const gchar* s_json_get_member_first(const gchar* json, const gchar** value)
{
  const gchar* key;
  const gchar* colon;
  const gchar* val;
  gint token;

  g_return_val_if_fail(json != NULL, NULL);
  g_return_val_if_fail(value != NULL, NULL);

  if (s_json_get_token(json, NULL, &key) != TOK_OBJ_START)
    return NULL;

  token = s_json_get_token(key, NULL, &colon);
  if (token != TOK_STRING && token != TOK_NOESC_STRING)
    return NULL;

  if (s_json_get_token(colon, NULL, &val) != TOK_COLON)
    return NULL;

  *value = val;
  return key;
}

const gchar* s_json_get_member_next(const gchar** value)
{
  const gchar* comma;
  const gchar* key;
  const gchar* colon;
  const gchar* val;
  gint token;

  g_return_val_if_fail(value != NULL && *value != NULL, NULL);

  if (!s_json_is_valid_inner(*value, &comma))
    return NULL;

  if (s_json_get_token(comma, NULL, &key) != TOK_COMMA)
    return NULL;

  token = s_json_get_token(key, NULL, &colon);
  if (token != TOK_STRING && token != TOK_NOESC_STRING)
    return NULL;

  if (s_json_get_token(colon, NULL, &val) != TOK_COLON)
    return NULL;

  *value = val;
  return key;
}

const gchar* s_json_get_member(const gchar* json, const gchar* name)
{
  g_return_val_if_fail(json != NULL, NULL);
  g_return_val_if_fail(name != NULL, NULL);

  S_JSON_FOREACH_MEMBER(json, key, value)

    if (s_json_string_match(key, name))
      return value;

  S_JSON_FOREACH_END()

  return NULL;
}

gchar* s_json_get_string(const gchar* json)
{
  const gchar* start;
  const gchar* end;
  gint token;

  g_return_val_if_fail(json != NULL, NULL);

  token = s_json_get_token(json, &start, &end);
  if (token != TOK_STRING && token != TOK_NOESC_STRING)
    return NULL;

  if (token == TOK_NOESC_STRING)
    return g_strndup(start + 1, (end - start) - 2);

  GString* str = g_string_sized_new(end - start);
  const guchar* c = (const guchar*)start + 1;
  const guchar* m = NULL;
  const guchar* s;

  while (TRUE)
  {
    s = c;


#line 804 "sjson.gen.c"
	{
		guchar yych;
		yych = (guchar)*c;
		if (yych <= '"') {
			if (yych <= 0x00) goto yy75;
			if (yych >= '"') goto yy73;
		} else {
			if (yych == '\\') goto yy71;
		}
		++c;
		yych = (guchar)*c;
		goto yy86;
yy70:
#line 481 "sjson.c"
		{
      g_string_append_len(str, s, c - s);
      continue;
    }
#line 823 "sjson.gen.c"
yy71:
		yych = (guchar)*(m = ++c);
		if (yych <= 'e') {
			if (yych <= '/') {
				if (yych == '"') goto yy78;
				if (yych >= '/') goto yy78;
			} else {
				if (yych <= '\\') {
					if (yych >= '\\') goto yy78;
				} else {
					if (yych == 'b') goto yy78;
				}
			}
		} else {
			if (yych <= 'q') {
				if (yych <= 'f') goto yy78;
				if (yych == 'n') goto yy78;
			} else {
				if (yych <= 's') {
					if (yych <= 'r') goto yy78;
				} else {
					if (yych <= 't') goto yy78;
					if (yych <= 'u') goto yy76;
				}
			}
		}
yy72:
#line 516 "sjson.c"
		{ 
      g_assert_not_reached();
    }
#line 855 "sjson.gen.c"
yy73:
		++c;
#line 512 "sjson.c"
		{
      return g_string_free(str, FALSE);
    }
#line 862 "sjson.gen.c"
yy75:
		yych = (guchar)*++c;
		goto yy72;
yy76:
		yych = (guchar)*++c;
		if (yych <= '@') {
			if (yych <= '/') goto yy77;
			if (yych <= '9') goto yy80;
		} else {
			if (yych <= 'F') goto yy80;
			if (yych <= '`') goto yy77;
			if (yych <= 'f') goto yy80;
		}
yy77:
		c = m;
		goto yy72;
yy78:
		++c;
#line 486 "sjson.c"
		{
      gchar ch = (gchar)s[1];

      if (ch == 'b')
        g_string_append_c(str, '\b');
      else if (ch == 'n')
        g_string_append_c(str, '\n');
      else if (ch == 'r')
        g_string_append_c(str, '\r');
      else if (ch == 't')
        g_string_append_c(str, '\t');
      else if (ch == 'f')
        g_string_append_c(str, '\f');
      else
        g_string_append_c(str, ch);

      continue;
    }
#line 900 "sjson.gen.c"
yy80:
		yych = (guchar)*++c;
		if (yych <= '@') {
			if (yych <= '/') goto yy77;
			if (yych >= ':') goto yy77;
		} else {
			if (yych <= 'F') goto yy81;
			if (yych <= '`') goto yy77;
			if (yych >= 'g') goto yy77;
		}
yy81:
		yych = (guchar)*++c;
		if (yych <= '@') {
			if (yych <= '/') goto yy77;
			if (yych >= ':') goto yy77;
		} else {
			if (yych <= 'F') goto yy82;
			if (yych <= '`') goto yy77;
			if (yych >= 'g') goto yy77;
		}
yy82:
		yych = (guchar)*++c;
		if (yych <= '@') {
			if (yych <= '/') goto yy77;
			if (yych >= ':') goto yy77;
		} else {
			if (yych <= 'F') goto yy83;
			if (yych <= '`') goto yy77;
			if (yych >= 'g') goto yy77;
		}
yy83:
		++c;
#line 505 "sjson.c"
		{
      guint ch = 0;
      sscanf(s + 2, "%4x", &ch);
      g_string_append_unichar(str, ch);
      continue;
    }
#line 940 "sjson.gen.c"
yy85:
		++c;
		yych = (guchar)*c;
yy86:
		if (yych <= '"') {
			if (yych <= 0x00) goto yy70;
			if (yych <= '!') goto yy85;
			goto yy70;
		} else {
			if (yych == '\\') goto yy70;
			goto yy85;
		}
	}
#line 519 "sjson.c"

  }

  return NULL;
}

gint64 s_json_get_int(const gchar* json, gint64 fallback)
{
  const gchar* start;
  const gchar* end;

  g_return_val_if_fail(json != NULL, fallback);

  if (s_json_get_token(json, &start, &end) != TOK_NUMBER)
    return fallback;

  gchar* str = g_alloca(end - start + 1);
  memcpy(str, start, end - start);
  str[end - start] = 0;

  gint64 v = fallback;
  sscanf(str, "%" G_GINT64_FORMAT, &v);
  return v;
}

gdouble s_json_get_double(const gchar* json, gdouble fallback)
{
  const gchar* start;
  const gchar* end;

  g_return_val_if_fail(json != NULL, fallback);

  if (s_json_get_token(json, &start, &end) != TOK_NUMBER)
    return fallback;

  gchar* str = g_alloca(end - start + 1);
  memcpy(str, start, end - start);
  str[end - start] = 0;

  gdouble v = fallback;
  sscanf(str, "%lf", &v);
  return v;
}

gboolean s_json_get_bool(const gchar* json)
{
  g_return_val_if_fail(json != NULL, FALSE);

  gint token = s_json_get_token(json, NULL, NULL);
  if (token == TOK_TRUE)
    return TRUE;

  return FALSE;
}

gboolean s_json_is_null(const gchar* json)
{
  g_return_val_if_fail(json != NULL, FALSE);

  gint token = s_json_get_token(json, NULL, NULL);
  if (token == TOK_NULL)
    return TRUE;

  return FALSE;
}

gboolean s_json_string_match(const gchar* json_str, const gchar* c_str)
{
  const gchar *start, *end;
  gint token;

  g_return_val_if_fail(json_str != NULL, FALSE);
  g_return_val_if_fail(c_str != NULL, FALSE);

  token = s_json_get_token(json_str, &start, &end);
  if (token == TOK_NOESC_STRING)
  {
    // fast path
    gsize json_len = ((end - start) - 2);
    gint rs = strncmp(start + 1, c_str, json_len);

    return rs == 0 ? strlen(c_str) == json_len : FALSE;
  }
  else if (token == TOK_STRING)
  {
    // slow path
    gchar* str = s_json_get_string(json_str);
    gint rs = strcmp(str, c_str);
    g_free(str);

    return rs == 0;
  }
  else
  {
    return FALSE;
  }
}

// helpers

gchar* s_json_get_member_string(const gchar* json, const gchar* name)
{
  g_return_val_if_fail(json != NULL, NULL);
  g_return_val_if_fail(name != NULL, NULL);

  const gchar* member = s_json_get_member(json, name);
  if (member)
    return s_json_get_string(member);

  return NULL;
}

gint64 s_json_get_member_int(const gchar* json, const gchar* name, gint64 fallback)
{
  g_return_val_if_fail(json != NULL, fallback);
  g_return_val_if_fail(name != NULL, fallback);

  const gchar* member = s_json_get_member(json, name);
  if (member)
    return s_json_get_int(member, fallback);

  return fallback;
}

gdouble s_json_get_member_double(const gchar* json, const gchar* name, gdouble fallback)
{
  g_return_val_if_fail(json != NULL, fallback);
  g_return_val_if_fail(name != NULL, fallback);

  const gchar* member = s_json_get_member(json, name);
  if (member)
    return s_json_get_double(member, fallback);

  return fallback;
}

gboolean s_json_get_member_bool(const gchar* json, const gchar* name)
{
  g_return_val_if_fail(json != NULL, FALSE);
  g_return_val_if_fail(name != NULL, FALSE);

  const gchar* member = s_json_get_member(json, name);
  if (member)
    return s_json_get_bool(member);

  return FALSE;
}

gboolean s_json_member_is_null(const gchar* json, const gchar* name)
{
  g_return_val_if_fail(json != NULL, FALSE);
  g_return_val_if_fail(name != NULL, FALSE);

  const gchar* member = s_json_get_member(json, name);
  if (member)
    return s_json_is_null(member);

  return TRUE;
}

// generator api

struct _SJsonGen
{
  GString* str;
};

SJsonGen* s_json_gen_new(void)
{
  SJsonGen* gen = g_slice_new(SJsonGen);
  gen->str = g_string_sized_new(512);
  return gen;
}

static void strip_comma(SJsonGen* json)
{
  if (json->str->len > 0)
  {
    if (json->str->str[json->str->len - 1] == ',')
      g_string_truncate(json->str, json->str->len - 1);
  }
}

void s_json_gen_start_object(SJsonGen* json)
{
  g_return_if_fail(json != NULL);

  g_string_append_c(json->str, '{');
}

void s_json_gen_end_object(SJsonGen* json)
{
  g_return_if_fail(json != NULL);

  strip_comma(json);
  g_string_append(json->str, "},");
}


void s_json_gen_start_array(SJsonGen* json)
{
  g_return_if_fail(json != NULL);

  g_string_append_c(json->str, '[');
}

void s_json_gen_end_array(SJsonGen* json)
{
  g_return_if_fail(json != NULL);

  strip_comma(json);
  g_string_append(json->str, "],");
}


static void escape_string(GString* str, const gchar* v)
{
  g_return_if_fail(str != NULL);
  g_return_if_fail(v != NULL);

  const guchar* c = (const guchar*)v;
  const guchar* m = NULL;
  const guchar* s;

  g_string_append_c(str, '"');

  while (TRUE)
  {
    s = c;


#line 1186 "sjson.gen.c"
	{
		guchar yych;
		yych = (guchar)*c;
		if (yych <= '\v') {
			if (yych <= 0x08) {
				if (yych <= 0x00) goto yy103;
				if (yych <= 0x07) goto yy105;
				goto yy93;
			} else {
				if (yych <= '\t') goto yy95;
				if (yych >= '\v') goto yy105;
			}
		} else {
			if (yych <= '!') {
				if (yych <= '\f') goto yy97;
				if (yych <= '\r') goto yy91;
				goto yy105;
			} else {
				if (yych <= '"') goto yy99;
				if (yych == '\\') goto yy101;
				goto yy105;
			}
		}
		++c;
#line 750 "sjson.c"
		{ g_string_append(str, "\\n"); continue; }
#line 1213 "sjson.gen.c"
yy91:
		++c;
#line 751 "sjson.c"
		{ g_string_append(str, "\\r"); continue; }
#line 1218 "sjson.gen.c"
yy93:
		++c;
#line 752 "sjson.c"
		{ g_string_append(str, "\\b"); continue; }
#line 1223 "sjson.gen.c"
yy95:
		++c;
#line 753 "sjson.c"
		{ g_string_append(str, "\\t"); continue; }
#line 1228 "sjson.gen.c"
yy97:
		++c;
		if ((yych = (guchar)*c) <= '\r') {
			if (yych <= 0x07) {
				if (yych >= 0x01) goto yy105;
			} else {
				if (yych <= '\n') goto yy98;
				if (yych <= '\f') goto yy105;
			}
		} else {
			if (yych <= '"') {
				if (yych <= '!') goto yy105;
			} else {
				if (yych != '\\') goto yy105;
			}
		}
yy98:
#line 754 "sjson.c"
		{ g_string_append(str, "\\f"); continue; }
#line 1248 "sjson.gen.c"
yy99:
		++c;
#line 755 "sjson.c"
		{ g_string_append(str, "\\\""); continue; }
#line 1253 "sjson.gen.c"
yy101:
		++c;
#line 756 "sjson.c"
		{ g_string_append(str, "\\\\"); continue; }
#line 1258 "sjson.gen.c"
yy103:
		++c;
#line 758 "sjson.c"
		{ 
    break;
  }
#line 1265 "sjson.gen.c"
yy105:
		++c;
		yych = (guchar)*c;
		if (yych <= '\r') {
			if (yych <= 0x07) {
				if (yych >= 0x01) goto yy105;
			} else {
				if (yych <= '\n') goto yy107;
				if (yych <= '\f') goto yy105;
			}
		} else {
			if (yych <= '"') {
				if (yych <= '!') goto yy105;
			} else {
				if (yych != '\\') goto yy105;
			}
		}
yy107:
#line 762 "sjson.c"
		{
    g_string_append_len(str, (gchar*)s, c - s);
    continue;
  }
#line 1289 "sjson.gen.c"
	}
#line 766 "sjson.c"

  }

  g_string_append_c(str, '"');
}

void s_json_gen_build(SJsonGen* json, const gchar* fmt, ...)
{
  va_list args;
  gchar* v;

  g_return_if_fail(json != NULL);
  g_return_if_fail(fmt != NULL);

  va_start(args, fmt);
  v = s_json_buildv(fmt, args);
  va_end(args);

  if (v)
  {
    g_string_append(json->str, v);
    g_string_append_c(json->str, ',');
  }
  else
    s_json_gen_null(json);

  g_free(v);
}

void s_json_gen_json(SJsonGen* json, const gchar* v)
{
  g_return_if_fail(json != NULL);

  if (v)
  {
    const gchar* end;

    if (s_json_is_valid_inner(v, &end))
      g_string_append_len(json->str, v, end - v); 
    else
      g_string_append(json->str, "null");

    g_string_append_c(json->str, ',');
  }
  else
    s_json_gen_null(json);
}

void s_json_gen_string(SJsonGen* json, const gchar* v)
{
  g_return_if_fail(json != NULL);

  if (v)
  {
    escape_string(json->str, v);
    g_string_append_c(json->str, ',');
  }
  else
    s_json_gen_null(json);
}

void s_json_gen_int(SJsonGen* json, gint64 v)
{
  g_return_if_fail(json != NULL);

  g_string_append_printf(json->str, "%" G_GINT64_FORMAT ",", v);
}

void s_json_gen_double(SJsonGen* json, gdouble v)
{
  g_return_if_fail(json != NULL);

  g_string_append_printf(json->str, "%lg,", v);
}

void s_json_gen_bool(SJsonGen* json, gboolean v)
{
  g_return_if_fail(json != NULL);

  g_string_append(json->str, v ? "true," : "false,");
}

void s_json_gen_null(SJsonGen* json)
{
  g_return_if_fail(json != NULL);

  g_string_append(json->str, "null,");
}


void s_json_gen_member_build(SJsonGen* json, const gchar* name, const gchar* fmt, ...)
{
  va_list args;
  gchar* v;

  g_return_if_fail(json != NULL);
  g_return_if_fail(name != NULL);
  g_return_if_fail(fmt != NULL);

  va_start(args, fmt);
  v = s_json_buildv(fmt, args);
  va_end(args);

  s_json_gen_member_json(json, name, v);

  g_free(v);
}

void s_json_gen_member(SJsonGen* json, const gchar* name)
{
  g_return_if_fail(json != NULL);
  g_return_if_fail(name != NULL);

  s_json_gen_string(json, name);
  strip_comma(json);
  g_string_append_c(json->str, ':');
}

void s_json_gen_member_json(SJsonGen* json, const gchar* name, const gchar* v)
{
  g_return_if_fail(json != NULL);
  g_return_if_fail(name != NULL);

  s_json_gen_string(json, name);
  strip_comma(json);
  g_string_append_c(json->str, ':');
  s_json_gen_json(json, v);
}

void s_json_gen_member_string(SJsonGen* json, const gchar* name, const gchar* v)
{
  g_return_if_fail(json != NULL);
  g_return_if_fail(name != NULL);

  s_json_gen_string(json, name);
  strip_comma(json);
  g_string_append_c(json->str, ':');
  s_json_gen_string(json, v);
}

void s_json_gen_member_int(SJsonGen* json, const gchar* name, gint64 v)
{
  g_return_if_fail(json != NULL);
  g_return_if_fail(name != NULL);

  s_json_gen_string(json, name);
  strip_comma(json);
  g_string_append_c(json->str, ':');
  s_json_gen_int(json, v);
}

void s_json_gen_member_double(SJsonGen* json, const gchar* name, gdouble v)
{
  g_return_if_fail(json != NULL);
  g_return_if_fail(name != NULL);

  s_json_gen_string(json, name);
  strip_comma(json);
  g_string_append_c(json->str, ':');
  s_json_gen_double(json, v);
}

void s_json_gen_member_bool(SJsonGen* json, const gchar* name, gboolean v)
{
  g_return_if_fail(json != NULL);
  g_return_if_fail(name != NULL);

  s_json_gen_string(json, name);
  strip_comma(json);
  g_string_append_c(json->str, ':');
  s_json_gen_bool(json, v);
}

void s_json_gen_member_null(SJsonGen* json, const gchar* name)
{
  g_return_if_fail(json != NULL);
  g_return_if_fail(name != NULL);

  s_json_gen_string(json, name);
  strip_comma(json);
  g_string_append_c(json->str, ':');
  s_json_gen_null(json);
}

void s_json_gen_member_array(SJsonGen* json, const gchar* name)
{
  g_return_if_fail(json != NULL);
  g_return_if_fail(name != NULL);

  s_json_gen_string(json, name);
  strip_comma(json);
  g_string_append_c(json->str, ':');
  s_json_gen_start_array(json);
}

void s_json_gen_member_object(SJsonGen* json, const gchar* name)
{
  g_return_if_fail(json != NULL);
  g_return_if_fail(name != NULL);

  s_json_gen_string(json, name);
  strip_comma(json);
  g_string_append_c(json->str, ':');
  s_json_gen_start_object(json);
}


gchar* s_json_gen_done(SJsonGen* json)
{
  g_return_val_if_fail(json != NULL, NULL);

  strip_comma(json);
  gchar* str = g_string_free(json->str, FALSE);
  g_slice_free(SJsonGen, json);

  if (s_json_is_valid(str))
    return str;

  g_free(str);
  return NULL;
}

void s_json_gen_free(SJsonGen* json)
{
  g_return_val_if_fail(json != NULL, NULL);

  g_string_free(json->str, TRUE);
  g_slice_free(SJsonGen, json);
}

// build

// formats:
// - % ? format
// format: sidbnjSJ

gchar* s_json_buildv(const gchar* format, va_list args)
{
  g_return_val_if_fail(format != NULL, NULL);

  GString* str = g_string_sized_new(strlen(format));
  const guchar* c = (const guchar*)format;
  const guchar* m = NULL;
  const guchar* cm = NULL;
  const guchar* s;

#define IS_NULLABLE (s[1] == '?')
#define FMT_FULL(arg_type, code_format, code_leave) \
  gboolean is_null = (IS_NULLABLE ? va_arg(args, gboolean) : FALSE); \
  gchar fmt = s[IS_NULLABLE ? 2 : 1]; \
  arg_type arg = va_arg(args, arg_type); \
  if (is_null) { \
    g_string_append(str, "null"); \
  } else { \
    code_format \
  } \
  code_leave \
  continue;

#define FMT(arg_type, code) FMT_FULL(arg_type, code, )

  while (TRUE)
  {
    s = c;


#line 1558 "sjson.gen.c"
	{
		guchar yych;
		unsigned int yyaccept = 0;
		yych = (guchar)*c;
		if (yych <= ':') {
			if (yych <= '"') {
				if (yych <= '\f') {
					if (yych <= 0x00) goto yy123;
					if (yych <= 0x08) goto yy125;
					if (yych >= '\v') goto yy125;
				} else {
					if (yych <= 0x1F) {
						if (yych >= 0x0E) goto yy125;
					} else {
						if (yych <= ' ') goto yy110;
						if (yych <= '!') goto yy125;
						goto yy112;
					}
				}
			} else {
				if (yych <= ',') {
					if (yych == '%') goto yy122;
					if (yych <= '+') goto yy125;
				} else {
					if (yych <= '/') {
						if (yych <= '-') goto yy114;
						goto yy125;
					} else {
						if (yych <= '0') goto yy116;
						if (yych <= '9') goto yy117;
					}
				}
			}
		} else {
			if (yych <= 'e') {
				if (yych <= '\\') {
					if (yych <= '@') goto yy125;
					if (yych <= 'Z') goto yy121;
					if (yych >= '\\') goto yy125;
				} else {
					if (yych <= '^') {
						if (yych >= '^') goto yy125;
					} else {
						if (yych == '`') goto yy125;
						goto yy121;
					}
				}
			} else {
				if (yych <= 't') {
					if (yych <= 'm') {
						if (yych <= 'f') goto yy119;
						goto yy121;
					} else {
						if (yych <= 'n') goto yy120;
						if (yych <= 's') goto yy121;
						goto yy118;
					}
				} else {
					if (yych <= '{') {
						if (yych <= 'z') goto yy121;
					} else {
						if (yych != '}') goto yy125;
					}
				}
			}
		}
yy110:
		yyaccept = 0;
		yych = (guchar)*(m = ++c);
		goto yy155;
yy111:
#line 1032 "sjson.c"
		{
      g_string_append_len(str, s, c - s);
      continue;
    }
#line 1635 "sjson.gen.c"
yy112:
		yyaccept = 1;
		yych = (guchar)*(m = ++c);
		if (yych >= 0x01) goto yy157;
yy113:
#line 1084 "sjson.c"
		{
      goto err;
    }
#line 1645 "sjson.gen.c"
yy114:
		++c;
		if ((yych = (guchar)*c) <= '/') goto yy139;
		if (yych <= '0') goto yy179;
		if (yych <= '9') goto yy181;
		goto yy139;
yy115:
#line 1042 "sjson.c"
		{
      g_string_append_c(str, '"');
      g_string_append_len(str, s, c - s);
      g_string_append_c(str, '"');
      continue;
    }
#line 1660 "sjson.gen.c"
yy116:
		yyaccept = 0;
		yych = (guchar)*(m = ++c);
		if (yych <= 'D') {
			if (yych == '.') goto yy152;
			goto yy155;
		} else {
			if (yych <= 'E') goto yy153;
			if (yych == 'e') goto yy153;
			goto yy155;
		}
yy117:
		yyaccept = 0;
		yych = (guchar)*(m = ++c);
		if (yych <= '0') {
			if (yych == '.') goto yy152;
			if (yych <= '/') goto yy155;
			goto yy150;
		} else {
			if (yych <= 'E') {
				if (yych <= 'D') goto yy155;
				goto yy153;
			} else {
				if (yych == 'e') goto yy153;
				goto yy155;
			}
		}
yy118:
		yych = (guchar)*++c;
		if (yych == 'r') goto yy148;
		goto yy139;
yy119:
		yych = (guchar)*++c;
		if (yych == 'a') goto yy145;
		goto yy139;
yy120:
		yych = (guchar)*++c;
		if (yych == 'u') goto yy140;
		goto yy139;
yy121:
		yych = (guchar)*++c;
		goto yy139;
yy122:
		yyaccept = 1;
		yych = (guchar)*(m = ++c);
		if (yych <= 'b') {
			if (yych <= 'J') {
				if (yych == '?') goto yy126;
				if (yych <= 'I') goto yy113;
				goto yy134;
			} else {
				if (yych == 'S') goto yy136;
				if (yych <= 'a') goto yy113;
				goto yy128;
			}
		} else {
			if (yych <= 'i') {
				if (yych == 'd') goto yy130;
				if (yych <= 'h') goto yy113;
				goto yy132;
			} else {
				if (yych <= 'j') goto yy134;
				if (yych == 's') goto yy136;
				goto yy113;
			}
		}
yy123:
		++c;
#line 1080 "sjson.c"
		{ 
      break;   
    }
#line 1733 "sjson.gen.c"
yy125:
		yych = (guchar)*++c;
		goto yy113;
yy126:
		yych = (guchar)*++c;
		if (yych <= 'c') {
			if (yych <= 'R') {
				if (yych == 'J') goto yy134;
			} else {
				if (yych <= 'S') goto yy136;
				if (yych == 'b') goto yy128;
			}
		} else {
			if (yych <= 'i') {
				if (yych <= 'd') goto yy130;
				if (yych >= 'i') goto yy132;
			} else {
				if (yych <= 'j') goto yy134;
				if (yych == 's') goto yy136;
			}
		}
yy127:
		c = m;
		if (yyaccept <= 1) {
			if (yyaccept <= 0) {
				goto yy111;
			} else {
				goto yy113;
			}
		} else {
			goto yy115;
		}
yy128:
		++c;
#line 1076 "sjson.c"
		{
      FMT(gboolean, g_string_append(str, arg ? "true" : "false");)
    }
#line 1772 "sjson.gen.c"
yy130:
		++c;
#line 1072 "sjson.c"
		{
      FMT(gdouble, g_string_append_printf(str, "%lg" , arg);)
    }
#line 1779 "sjson.gen.c"
yy132:
		++c;
#line 1068 "sjson.c"
		{
      FMT(gint64, g_string_append_printf(str, "%" G_GINT64_FORMAT, arg);)
    }
#line 1786 "sjson.gen.c"
yy134:
		++c;
#line 1055 "sjson.c"
		{
      FMT_FULL(gchar*, 
        if (arg) {
          const gchar* end;
          if (s_json_is_valid_inner(arg, &end))
            g_string_append_len(str, arg, end - arg); 
          else
            g_string_append(str, "null");
        } else {
          g_string_append(str, "null");
        }, if (fmt == 'J') g_free(arg);)
    }
#line 1802 "sjson.gen.c"
yy136:
		++c;
#line 1051 "sjson.c"
		{
      FMT_FULL(gchar*, if (arg) escape_string(str, arg); else g_string_append(str, "null");, if (fmt == 'S') g_free(arg);)
    }
#line 1809 "sjson.gen.c"
yy138:
		++c;
		yych = (guchar)*c;
yy139:
		if (yych <= '@') {
			if (yych <= '-') {
				if (yych <= ',') goto yy115;
				goto yy138;
			} else {
				if (yych <= '/') goto yy115;
				if (yych <= '9') goto yy138;
				goto yy115;
			}
		} else {
			if (yych <= '_') {
				if (yych <= 'Z') goto yy138;
				if (yych <= '^') goto yy115;
				goto yy138;
			} else {
				if (yych <= '`') goto yy115;
				if (yych <= 'z') goto yy138;
				goto yy115;
			}
		}
yy140:
		yych = (guchar)*++c;
		if (yych != 'l') goto yy139;
		yych = (guchar)*++c;
		if (yych != 'l') goto yy139;
yy142:
		cm = c + 1;
		yych = (guchar)*++c;
		if (yych <= '@') {
			if (yych <= '-') {
				if (yych >= '-') goto yy138;
			} else {
				if (yych <= '/') goto yy143;
				if (yych <= '9') goto yy138;
			}
		} else {
			if (yych <= '_') {
				if (yych <= 'Z') goto yy138;
				if (yych >= '_') goto yy138;
			} else {
				if (yych <= '`') goto yy143;
				if (yych <= 'z') goto yy138;
			}
		}
yy143:
		++c;
		c = cm;
#line 1037 "sjson.c"
		{
      g_string_append_len(str, s, c - s);
      continue;
    }
#line 1866 "sjson.gen.c"
yy145:
		yych = (guchar)*++c;
		if (yych != 'l') goto yy139;
		yych = (guchar)*++c;
		if (yych != 's') goto yy139;
		yych = (guchar)*++c;
		if (yych == 'e') goto yy142;
		goto yy139;
yy148:
		yych = (guchar)*++c;
		if (yych != 'u') goto yy139;
		yych = (guchar)*++c;
		if (yych == 'e') goto yy142;
		goto yy139;
yy150:
		yyaccept = 0;
		m = ++c;
		yych = (guchar)*c;
		if (yych <= '9') {
			if (yych <= '!') {
				if (yych <= '\f') {
					if (yych <= 0x08) goto yy111;
					if (yych <= '\n') goto yy154;
					goto yy111;
				} else {
					if (yych <= '\r') goto yy154;
					if (yych == ' ') goto yy154;
					goto yy111;
				}
			} else {
				if (yych <= ',') {
					if (yych <= '"') goto yy156;
					if (yych <= '+') goto yy111;
					goto yy154;
				} else {
					if (yych <= '-') goto yy158;
					if (yych <= '.') goto yy152;
					if (yych <= '/') goto yy111;
					goto yy150;
				}
			}
		} else {
			if (yych <= ']') {
				if (yych <= 'E') {
					if (yych <= ':') goto yy154;
					if (yych <= 'D') goto yy111;
					goto yy153;
				} else {
					if (yych == '[') goto yy154;
					if (yych <= '\\') goto yy111;
					goto yy154;
				}
			} else {
				if (yych <= 'z') {
					if (yych == 'e') goto yy153;
					goto yy111;
				} else {
					if (yych == '|') goto yy111;
					if (yych <= '}') goto yy154;
					goto yy111;
				}
			}
		}
yy152:
		++c;
		yych = (guchar)*c;
		if (yych <= '/') goto yy127;
		if (yych <= '9') goto yy174;
		goto yy127;
yy153:
		++c;
		yych = (guchar)*c;
		if (yych <= ',') {
			if (yych == '+') goto yy168;
			goto yy127;
		} else {
			if (yych <= '-') goto yy168;
			if (yych <= '/') goto yy127;
			if (yych <= '9') goto yy169;
			goto yy127;
		}
yy154:
		yyaccept = 0;
		m = ++c;
		yych = (guchar)*c;
yy155:
		if (yych <= '/') {
			if (yych <= ' ') {
				if (yych <= '\f') {
					if (yych <= 0x08) goto yy111;
					if (yych <= '\n') goto yy154;
					goto yy111;
				} else {
					if (yych <= '\r') goto yy154;
					if (yych <= 0x1F) goto yy111;
					goto yy154;
				}
			} else {
				if (yych <= '+') {
					if (yych != '"') goto yy111;
				} else {
					if (yych <= ',') goto yy154;
					if (yych <= '-') goto yy158;
					goto yy111;
				}
			}
		} else {
			if (yych <= '\\') {
				if (yych <= ':') {
					if (yych <= '0') goto yy159;
					if (yych <= '9') goto yy150;
					goto yy154;
				} else {
					if (yych == '[') goto yy154;
					goto yy111;
				}
			} else {
				if (yych <= '{') {
					if (yych <= ']') goto yy154;
					if (yych <= 'z') goto yy111;
					goto yy154;
				} else {
					if (yych == '}') goto yy154;
					goto yy111;
				}
			}
		}
yy156:
		++c;
		yych = (guchar)*c;
yy157:
		if (yych <= '"') {
			if (yych <= 0x00) goto yy127;
			if (yych <= '!') goto yy156;
			goto yy154;
		} else {
			if (yych == '\\') goto yy161;
			goto yy156;
		}
yy158:
		++c;
		yych = (guchar)*c;
		if (yych <= '/') goto yy127;
		if (yych <= '0') goto yy159;
		if (yych <= '9') goto yy150;
		goto yy127;
yy159:
		yyaccept = 0;
		m = ++c;
		yych = (guchar)*c;
		if (yych <= '0') {
			if (yych <= '!') {
				if (yych <= '\f') {
					if (yych <= 0x08) goto yy111;
					if (yych <= '\n') goto yy154;
					goto yy111;
				} else {
					if (yych <= '\r') goto yy154;
					if (yych == ' ') goto yy154;
					goto yy111;
				}
			} else {
				if (yych <= ',') {
					if (yych <= '"') goto yy156;
					if (yych <= '+') goto yy111;
					goto yy154;
				} else {
					if (yych <= '-') goto yy158;
					if (yych <= '.') goto yy152;
					if (yych <= '/') goto yy111;
					goto yy159;
				}
			}
		} else {
			if (yych <= '\\') {
				if (yych <= 'D') {
					if (yych <= '9') goto yy150;
					if (yych <= ':') goto yy154;
					goto yy111;
				} else {
					if (yych <= 'E') goto yy153;
					if (yych == '[') goto yy154;
					goto yy111;
				}
			} else {
				if (yych <= 'z') {
					if (yych <= ']') goto yy154;
					if (yych == 'e') goto yy153;
					goto yy111;
				} else {
					if (yych == '|') goto yy111;
					if (yych <= '}') goto yy154;
					goto yy111;
				}
			}
		}
yy161:
		++c;
		yych = (guchar)*c;
		if (yych <= 'e') {
			if (yych <= '/') {
				if (yych == '"') goto yy163;
				if (yych <= '.') goto yy127;
				goto yy163;
			} else {
				if (yych <= '\\') {
					if (yych <= '[') goto yy127;
					goto yy163;
				} else {
					if (yych == 'b') goto yy163;
					goto yy127;
				}
			}
		} else {
			if (yych <= 'q') {
				if (yych <= 'f') goto yy163;
				if (yych == 'n') goto yy163;
				goto yy127;
			} else {
				if (yych <= 's') {
					if (yych <= 'r') goto yy163;
					goto yy127;
				} else {
					if (yych <= 't') goto yy163;
					if (yych >= 'v') goto yy127;
				}
			}
		}
		++c;
		yych = (guchar)*c;
		if (yych <= '@') {
			if (yych <= '/') goto yy127;
			if (yych <= '9') goto yy165;
			goto yy127;
		} else {
			if (yych <= 'F') goto yy165;
			if (yych <= '`') goto yy127;
			if (yych <= 'f') goto yy165;
			goto yy127;
		}
yy163:
		++c;
		yych = (guchar)*c;
		if (yych <= '"') {
			if (yych <= 0x00) goto yy127;
			if (yych <= '!') goto yy163;
			goto yy154;
		} else {
			if (yych == '\\') goto yy161;
			goto yy163;
		}
yy165:
		++c;
		yych = (guchar)*c;
		if (yych <= '@') {
			if (yych <= '/') goto yy127;
			if (yych >= ':') goto yy127;
		} else {
			if (yych <= 'F') goto yy166;
			if (yych <= '`') goto yy127;
			if (yych >= 'g') goto yy127;
		}
yy166:
		++c;
		yych = (guchar)*c;
		if (yych <= '@') {
			if (yych <= '/') goto yy127;
			if (yych >= ':') goto yy127;
		} else {
			if (yych <= 'F') goto yy167;
			if (yych <= '`') goto yy127;
			if (yych >= 'g') goto yy127;
		}
yy167:
		++c;
		yych = (guchar)*c;
		if (yych <= '@') {
			if (yych <= '/') goto yy127;
			if (yych <= '9') goto yy163;
			goto yy127;
		} else {
			if (yych <= 'F') goto yy163;
			if (yych <= '`') goto yy127;
			if (yych <= 'f') goto yy163;
			goto yy127;
		}
yy168:
		++c;
		yych = (guchar)*c;
		if (yych <= '/') goto yy127;
		if (yych >= ':') goto yy127;
yy169:
		yyaccept = 0;
		m = ++c;
		yych = (guchar)*c;
		if (yych <= '/') {
			if (yych <= ' ') {
				if (yych <= '\f') {
					if (yych <= 0x08) goto yy111;
					if (yych <= '\n') goto yy154;
					goto yy111;
				} else {
					if (yych <= '\r') goto yy154;
					if (yych <= 0x1F) goto yy111;
					goto yy154;
				}
			} else {
				if (yych <= '+') {
					if (yych == '"') goto yy156;
					goto yy111;
				} else {
					if (yych <= ',') goto yy154;
					if (yych <= '-') goto yy158;
					goto yy111;
				}
			}
		} else {
			if (yych <= '\\') {
				if (yych <= ':') {
					if (yych <= '0') goto yy170;
					if (yych <= '9') goto yy172;
					goto yy154;
				} else {
					if (yych == '[') goto yy154;
					goto yy111;
				}
			} else {
				if (yych <= '{') {
					if (yych <= ']') goto yy154;
					if (yych <= 'z') goto yy111;
					goto yy154;
				} else {
					if (yych == '}') goto yy154;
					goto yy111;
				}
			}
		}
yy170:
		yyaccept = 0;
		m = ++c;
		yych = (guchar)*c;
		if (yych <= '0') {
			if (yych <= '!') {
				if (yych <= '\f') {
					if (yych <= 0x08) goto yy111;
					if (yych <= '\n') goto yy154;
					goto yy111;
				} else {
					if (yych <= '\r') goto yy154;
					if (yych == ' ') goto yy154;
					goto yy111;
				}
			} else {
				if (yych <= ',') {
					if (yych <= '"') goto yy156;
					if (yych <= '+') goto yy111;
					goto yy154;
				} else {
					if (yych <= '-') goto yy158;
					if (yych <= '.') goto yy152;
					if (yych <= '/') goto yy111;
					goto yy170;
				}
			}
		} else {
			if (yych <= '\\') {
				if (yych <= 'D') {
					if (yych <= '9') goto yy172;
					if (yych <= ':') goto yy154;
					goto yy111;
				} else {
					if (yych <= 'E') goto yy153;
					if (yych == '[') goto yy154;
					goto yy111;
				}
			} else {
				if (yych <= 'z') {
					if (yych <= ']') goto yy154;
					if (yych == 'e') goto yy153;
					goto yy111;
				} else {
					if (yych == '|') goto yy111;
					if (yych <= '}') goto yy154;
					goto yy111;
				}
			}
		}
yy172:
		yyaccept = 0;
		m = ++c;
		yych = (guchar)*c;
		if (yych <= '9') {
			if (yych <= '!') {
				if (yych <= '\f') {
					if (yych <= 0x08) goto yy111;
					if (yych <= '\n') goto yy154;
					goto yy111;
				} else {
					if (yych <= '\r') goto yy154;
					if (yych == ' ') goto yy154;
					goto yy111;
				}
			} else {
				if (yych <= ',') {
					if (yych <= '"') goto yy156;
					if (yych <= '+') goto yy111;
					goto yy154;
				} else {
					if (yych <= '-') goto yy158;
					if (yych <= '.') goto yy152;
					if (yych <= '/') goto yy111;
					goto yy172;
				}
			}
		} else {
			if (yych <= ']') {
				if (yych <= 'E') {
					if (yych <= ':') goto yy154;
					if (yych <= 'D') goto yy111;
					goto yy153;
				} else {
					if (yych == '[') goto yy154;
					if (yych <= '\\') goto yy111;
					goto yy154;
				}
			} else {
				if (yych <= 'z') {
					if (yych == 'e') goto yy153;
					goto yy111;
				} else {
					if (yych == '|') goto yy111;
					if (yych <= '}') goto yy154;
					goto yy111;
				}
			}
		}
yy174:
		yyaccept = 0;
		m = ++c;
		yych = (guchar)*c;
		if (yych <= '9') {
			if (yych <= '!') {
				if (yych <= '\f') {
					if (yych <= 0x08) goto yy111;
					if (yych <= '\n') goto yy154;
					goto yy111;
				} else {
					if (yych <= '\r') goto yy154;
					if (yych == ' ') goto yy154;
					goto yy111;
				}
			} else {
				if (yych <= ',') {
					if (yych <= '"') goto yy156;
					if (yych <= '+') goto yy111;
					goto yy154;
				} else {
					if (yych <= '-') goto yy158;
					if (yych <= '/') goto yy111;
					if (yych >= '1') goto yy177;
				}
			}
		} else {
			if (yych <= ']') {
				if (yych <= 'E') {
					if (yych <= ':') goto yy154;
					if (yych <= 'D') goto yy111;
					goto yy153;
				} else {
					if (yych == '[') goto yy154;
					if (yych <= '\\') goto yy111;
					goto yy154;
				}
			} else {
				if (yych <= 'z') {
					if (yych == 'e') goto yy153;
					goto yy111;
				} else {
					if (yych == '|') goto yy111;
					if (yych <= '}') goto yy154;
					goto yy111;
				}
			}
		}
yy175:
		yyaccept = 0;
		m = ++c;
		yych = (guchar)*c;
		if (yych <= '0') {
			if (yych <= '!') {
				if (yych <= '\f') {
					if (yych <= 0x08) goto yy111;
					if (yych <= '\n') goto yy154;
					goto yy111;
				} else {
					if (yych <= '\r') goto yy154;
					if (yych == ' ') goto yy154;
					goto yy111;
				}
			} else {
				if (yych <= ',') {
					if (yych <= '"') goto yy156;
					if (yych <= '+') goto yy111;
					goto yy154;
				} else {
					if (yych <= '-') goto yy158;
					if (yych <= '.') goto yy152;
					if (yych <= '/') goto yy111;
					goto yy175;
				}
			}
		} else {
			if (yych <= '\\') {
				if (yych <= 'D') {
					if (yych <= '9') goto yy177;
					if (yych <= ':') goto yy154;
					goto yy111;
				} else {
					if (yych <= 'E') goto yy153;
					if (yych == '[') goto yy154;
					goto yy111;
				}
			} else {
				if (yych <= 'z') {
					if (yych <= ']') goto yy154;
					if (yych == 'e') goto yy153;
					goto yy111;
				} else {
					if (yych == '|') goto yy111;
					if (yych <= '}') goto yy154;
					goto yy111;
				}
			}
		}
yy177:
		yyaccept = 0;
		m = ++c;
		yych = (guchar)*c;
		if (yych <= '9') {
			if (yych <= '!') {
				if (yych <= '\f') {
					if (yych <= 0x08) goto yy111;
					if (yych <= '\n') goto yy154;
					goto yy111;
				} else {
					if (yych <= '\r') goto yy154;
					if (yych == ' ') goto yy154;
					goto yy111;
				}
			} else {
				if (yych <= ',') {
					if (yych <= '"') goto yy156;
					if (yych <= '+') goto yy111;
					goto yy154;
				} else {
					if (yych <= '-') goto yy158;
					if (yych <= '.') goto yy152;
					if (yych <= '/') goto yy111;
					goto yy177;
				}
			}
		} else {
			if (yych <= ']') {
				if (yych <= 'E') {
					if (yych <= ':') goto yy154;
					if (yych <= 'D') goto yy111;
					goto yy153;
				} else {
					if (yych == '[') goto yy154;
					if (yych <= '\\') goto yy111;
					goto yy154;
				}
			} else {
				if (yych <= 'z') {
					if (yych == 'e') goto yy153;
					goto yy111;
				} else {
					if (yych == '|') goto yy111;
					if (yych <= '}') goto yy154;
					goto yy111;
				}
			}
		}
yy179:
		yyaccept = 0;
		m = ++c;
		yych = (guchar)*c;
		if (yych <= ':') {
			if (yych <= '"') {
				if (yych <= '\r') {
					if (yych <= 0x08) goto yy111;
					if (yych <= '\n') goto yy154;
					if (yych <= '\f') goto yy111;
					goto yy154;
				} else {
					if (yych == ' ') goto yy154;
					if (yych <= '!') goto yy111;
					goto yy156;
				}
			} else {
				if (yych <= '.') {
					if (yych <= '+') goto yy111;
					if (yych <= ',') goto yy154;
					if (yych <= '-') goto yy184;
					goto yy152;
				} else {
					if (yych <= '/') goto yy111;
					if (yych <= '0') goto yy179;
					if (yych >= ':') goto yy154;
				}
			}
		} else {
			if (yych <= '^') {
				if (yych <= 'Z') {
					if (yych <= '@') goto yy111;
					if (yych == 'E') goto yy183;
					goto yy138;
				} else {
					if (yych == '\\') goto yy111;
					if (yych <= ']') goto yy154;
					goto yy111;
				}
			} else {
				if (yych <= 'e') {
					if (yych == '`') goto yy111;
					if (yych <= 'd') goto yy138;
					goto yy183;
				} else {
					if (yych <= '{') {
						if (yych <= 'z') goto yy138;
						goto yy154;
					} else {
						if (yych == '}') goto yy154;
						goto yy111;
					}
				}
			}
		}
yy181:
		yyaccept = 0;
		m = ++c;
		yych = (guchar)*c;
		if (yych <= '@') {
			if (yych <= '"') {
				if (yych <= '\r') {
					if (yych <= 0x08) goto yy111;
					if (yych <= '\n') goto yy154;
					if (yych <= '\f') goto yy111;
					goto yy154;
				} else {
					if (yych == ' ') goto yy154;
					if (yych <= '!') goto yy111;
					goto yy156;
				}
			} else {
				if (yych <= '.') {
					if (yych <= '+') goto yy111;
					if (yych <= ',') goto yy154;
					if (yych <= '-') goto yy184;
					goto yy152;
				} else {
					if (yych <= '/') goto yy111;
					if (yych <= '9') goto yy181;
					if (yych <= ':') goto yy154;
					goto yy111;
				}
			}
		} else {
			if (yych <= '_') {
				if (yych <= '[') {
					if (yych == 'E') goto yy183;
					if (yych <= 'Z') goto yy138;
					goto yy154;
				} else {
					if (yych == ']') goto yy154;
					if (yych <= '^') goto yy111;
					goto yy138;
				}
			} else {
				if (yych <= 'z') {
					if (yych <= '`') goto yy111;
					if (yych != 'e') goto yy138;
				} else {
					if (yych == '|') goto yy111;
					if (yych <= '}') goto yy154;
					goto yy111;
				}
			}
		}
yy183:
		yyaccept = 2;
		m = ++c;
		yych = (guchar)*c;
		if (yych <= '9') {
			if (yych <= ',') {
				if (yych == '+') goto yy168;
				goto yy115;
			} else {
				if (yych <= '-') goto yy185;
				if (yych <= '/') goto yy115;
				goto yy186;
			}
		} else {
			if (yych <= '^') {
				if (yych <= '@') goto yy115;
				if (yych <= 'Z') goto yy138;
				goto yy115;
			} else {
				if (yych == '`') goto yy115;
				if (yych <= 'z') goto yy138;
				goto yy115;
			}
		}
yy184:
		++c;
		yych = (guchar)*c;
		if (yych <= '@') {
			if (yych <= '/') {
				if (yych == '-') goto yy138;
				goto yy115;
			} else {
				if (yych <= '0') goto yy179;
				if (yych <= '9') goto yy181;
				goto yy115;
			}
		} else {
			if (yych <= '_') {
				if (yych <= 'Z') goto yy138;
				if (yych <= '^') goto yy115;
				goto yy138;
			} else {
				if (yych <= '`') goto yy115;
				if (yych <= 'z') goto yy138;
				goto yy115;
			}
		}
yy185:
		++c;
		yych = (guchar)*c;
		if (yych <= '@') {
			if (yych <= '-') {
				if (yych <= ',') goto yy115;
				goto yy138;
			} else {
				if (yych <= '/') goto yy115;
				if (yych >= ':') goto yy115;
			}
		} else {
			if (yych <= '_') {
				if (yych <= 'Z') goto yy138;
				if (yych <= '^') goto yy115;
				goto yy138;
			} else {
				if (yych <= '`') goto yy115;
				if (yych <= 'z') goto yy138;
				goto yy115;
			}
		}
yy186:
		yyaccept = 0;
		m = ++c;
		yych = (guchar)*c;
		if (yych <= '9') {
			if (yych <= '!') {
				if (yych <= '\f') {
					if (yych <= 0x08) goto yy111;
					if (yych <= '\n') goto yy154;
					goto yy111;
				} else {
					if (yych <= '\r') goto yy154;
					if (yych == ' ') goto yy154;
					goto yy111;
				}
			} else {
				if (yych <= ',') {
					if (yych <= '"') goto yy156;
					if (yych <= '+') goto yy111;
					goto yy154;
				} else {
					if (yych <= '-') goto yy184;
					if (yych <= '/') goto yy111;
					if (yych >= '1') goto yy189;
				}
			}
		} else {
			if (yych <= '^') {
				if (yych <= 'Z') {
					if (yych <= ':') goto yy154;
					if (yych <= '@') goto yy111;
					goto yy138;
				} else {
					if (yych == '\\') goto yy111;
					if (yych <= ']') goto yy154;
					goto yy111;
				}
			} else {
				if (yych <= 'z') {
					if (yych == '`') goto yy111;
					goto yy138;
				} else {
					if (yych == '|') goto yy111;
					if (yych <= '}') goto yy154;
					goto yy111;
				}
			}
		}
yy187:
		yyaccept = 0;
		m = ++c;
		yych = (guchar)*c;
		if (yych <= ':') {
			if (yych <= '"') {
				if (yych <= '\r') {
					if (yych <= 0x08) goto yy111;
					if (yych <= '\n') goto yy154;
					if (yych <= '\f') goto yy111;
					goto yy154;
				} else {
					if (yych == ' ') goto yy154;
					if (yych <= '!') goto yy111;
					goto yy156;
				}
			} else {
				if (yych <= '.') {
					if (yych <= '+') goto yy111;
					if (yych <= ',') goto yy154;
					if (yych <= '-') goto yy184;
					goto yy152;
				} else {
					if (yych <= '/') goto yy111;
					if (yych <= '0') goto yy187;
					if (yych >= ':') goto yy154;
				}
			}
		} else {
			if (yych <= '^') {
				if (yych <= 'Z') {
					if (yych <= '@') goto yy111;
					if (yych == 'E') goto yy183;
					goto yy138;
				} else {
					if (yych == '\\') goto yy111;
					if (yych <= ']') goto yy154;
					goto yy111;
				}
			} else {
				if (yych <= 'e') {
					if (yych == '`') goto yy111;
					if (yych <= 'd') goto yy138;
					goto yy183;
				} else {
					if (yych <= '{') {
						if (yych <= 'z') goto yy138;
						goto yy154;
					} else {
						if (yych == '}') goto yy154;
						goto yy111;
					}
				}
			}
		}
yy189:
		yyaccept = 0;
		m = ++c;
		yych = (guchar)*c;
		if (yych <= '@') {
			if (yych <= '"') {
				if (yych <= '\r') {
					if (yych <= 0x08) goto yy111;
					if (yych <= '\n') goto yy154;
					if (yych <= '\f') goto yy111;
					goto yy154;
				} else {
					if (yych == ' ') goto yy154;
					if (yych <= '!') goto yy111;
					goto yy156;
				}
			} else {
				if (yych <= '.') {
					if (yych <= '+') goto yy111;
					if (yych <= ',') goto yy154;
					if (yych <= '-') goto yy184;
					goto yy152;
				} else {
					if (yych <= '/') goto yy111;
					if (yych <= '9') goto yy189;
					if (yych <= ':') goto yy154;
					goto yy111;
				}
			}
		} else {
			if (yych <= '_') {
				if (yych <= '[') {
					if (yych == 'E') goto yy183;
					if (yych <= 'Z') goto yy138;
					goto yy154;
				} else {
					if (yych == ']') goto yy154;
					if (yych <= '^') goto yy111;
					goto yy138;
				}
			} else {
				if (yych <= 'z') {
					if (yych <= '`') goto yy111;
					if (yych == 'e') goto yy183;
					goto yy138;
				} else {
					if (yych == '|') goto yy111;
					if (yych <= '}') goto yy154;
					goto yy111;
				}
			}
		}
	}
#line 1087 "sjson.c"

  }

  if (s_json_is_valid(str->str))
    return g_string_free(str, FALSE);

err:
  g_string_free(str, TRUE);
  return NULL;
}

gchar* s_json_build(const gchar* format, ...)
{
  va_list args;
  gchar* json;

  g_return_val_if_fail(format != NULL, NULL);

  va_start(args, format);
  json = s_json_buildv(format, args);
  va_end(args);

  return json;
}

gchar* s_json_pretty(const gchar* json)
{
  const gchar* start;
  const gchar* end;
  const gchar* json_end;
  GString *str, *ind;

  g_return_val_if_fail(json != NULL, NULL);

  // validate and isolate
  if (!s_json_is_valid_inner(json, &json_end))
    return NULL;

  start = json;

  str = g_string_sized_new(strlen(json) * 2);
  ind = g_string_sized_new(50);

#define PUSH_INDENT() g_string_append_c(ind, '\t')
#define POP_INDENT() g_string_truncate(ind, MAX(ind->len - 1, 0))
#define INDENT() g_string_append_len(str, ind->str, ind->len)

  gint prev_token = TOK_NONE;
  while (TRUE)
  {
    // if next token starts at the end of the fragment, end the loop
    if (json_end == start)
      break;

    gint token = s_json_get_token(start, &start, &end);
    if (token == TOK_NONE)
      break;

    gint next_token = s_json_get_token(end, NULL, NULL);

    if ((token == TOK_OBJ_END && prev_token != TOK_OBJ_START) || (token == TOK_ARRAY_END && prev_token != TOK_ARRAY_START && prev_token != TOK_OBJ_END))
    {
      g_string_append_c(str, '\n');
      POP_INDENT();
      INDENT();
    }

    g_string_append_len(str, start, end - start);

    if ((token == TOK_OBJ_START && next_token != TOK_OBJ_END) || (token == TOK_ARRAY_START && next_token != TOK_OBJ_START && next_token != TOK_ARRAY_END))
    {
      g_string_append_c(str, '\n');
      PUSH_INDENT();
      INDENT();
    }
    else if (token == TOK_COMMA)
    {
      if ((prev_token == TOK_OBJ_END && next_token == TOK_OBJ_START) || (prev_token == TOK_ARRAY_END && next_token == TOK_ARRAY_START))
      {
        g_string_append_c(str, ' ');
      }
      else
      {
        g_string_append_c(str, '\n');
        INDENT();
      }
    }
    else if (token == TOK_COLON)
    {
      g_string_append_c(str, ' ');
    }

    prev_token = token;
    start = end;
  }

  g_string_free(ind, TRUE);

  return g_string_free(str, FALSE);
}

const gchar* s_json_path(const gchar* json, const gchar* path)
{
  const guchar* c = (const guchar*)path;
  const guchar* m = NULL;
  const guchar* s;
  const gchar* cur_node = json;

  g_return_val_if_fail(json != NULL, NULL);
  g_return_val_if_fail(path != NULL, NULL);

#define CHECK_TYPE(type) \
  if (cur_node && s_json_get_type(cur_node) == type) \
    return cur_node; \
  if ((!cur_node || s_json_get_type(cur_node) == S_JSON_TYPE_NULL) && s[0] == '?') \
    return "null"; \
  return NULL;

  while (TRUE)
  {
    s = c;


#line 2905 "sjson.gen.c"
	{
		guchar yych;
		unsigned int yyaccept = 0;
		yych = (guchar)*c;
		if (yych <= '!') {
			if (yych <= '\f') {
				if (yych <= 0x00) goto yy201;
				if (yych <= 0x08) goto yy203;
				if (yych >= '\v') goto yy203;
			} else {
				if (yych <= '\r') goto yy193;
				if (yych <= 0x1F) goto yy203;
				if (yych >= '!') goto yy200;
			}
		} else {
			if (yych <= '.') {
				if (yych == '$') goto yy195;
				if (yych <= '-') goto yy203;
				goto yy197;
			} else {
				if (yych <= '?') {
					if (yych <= '>') goto yy203;
					goto yy200;
				} else {
					if (yych == '[') goto yy199;
					goto yy203;
				}
			}
		}
yy193:
		++c;
		yych = (guchar)*c;
		goto yy257;
yy194:
#line 1210 "sjson.c"
		{
      // skip whitespace
      continue;
    }
#line 2945 "sjson.gen.c"
yy195:
		++c;
#line 1215 "sjson.c"
		{
      // root
      cur_node = json;
      continue;
    }
#line 2954 "sjson.gen.c"
yy197:
		++c;
		if ((yych = (guchar)*c) <= 'Z') {
			if (yych == '-') goto yy253;
			if (yych >= 'A') goto yy253;
		} else {
			if (yych <= '_') {
				if (yych >= '_') goto yy253;
			} else {
				if (yych <= '`') goto yy198;
				if (yych <= 'z') goto yy253;
			}
		}
yy198:
#line 1288 "sjson.c"
		{
      return NULL;
    }
#line 2973 "sjson.gen.c"
yy199:
		yyaccept = 0;
		yych = (guchar)*(m = ++c);
		if (yych <= '/') goto yy198;
		if (yych <= '0') goto yy248;
		if (yych <= '9') goto yy249;
		goto yy198;
yy200:
		yych = (guchar)*++c;
		switch (yych) {
		case 'a':	goto yy204;
		case 'b':	goto yy208;
		case 'i':	goto yy210;
		case 'n':	goto yy214;
		case 'o':	goto yy206;
		case 's':	goto yy212;
		default:	goto yy198;
		}
yy201:
		++c;
#line 1284 "sjson.c"
		{ 
      break;
    }
#line 2998 "sjson.gen.c"
yy203:
		yych = (guchar)*++c;
		goto yy198;
yy204:
		yyaccept = 1;
		yych = (guchar)*(m = ++c);
		if (yych == 'r') goto yy244;
yy205:
#line 1280 "sjson.c"
		{
      CHECK_TYPE(S_JSON_TYPE_ARRAY)
    }
#line 3011 "sjson.gen.c"
yy206:
		yyaccept = 2;
		yych = (guchar)*(m = ++c);
		if (yych == 'b') goto yy239;
yy207:
#line 1276 "sjson.c"
		{
      CHECK_TYPE(S_JSON_TYPE_OBJECT)
    }
#line 3021 "sjson.gen.c"
yy208:
		yyaccept = 3;
		yych = (guchar)*(m = ++c);
		if (yych == 'o') goto yy233;
yy209:
#line 1272 "sjson.c"
		{
      CHECK_TYPE(S_JSON_TYPE_BOOL)
    }
#line 3031 "sjson.gen.c"
yy210:
		yyaccept = 4;
		yych = (guchar)*(m = ++c);
		if (yych == 'n') goto yy227;
yy211:
#line 1255 "sjson.c"
		{
      if (cur_node && s_json_get_type(cur_node) == S_JSON_TYPE_NUMBER)
      {
        const gchar *int_start, *int_end, *i;
        g_assert(s_json_get_token(cur_node, &int_start, &int_end) == TOK_NUMBER);
        for (i = int_start; i < int_end; i++)
          if (*i > '9' || *i < '0')
            return NULL;
        return cur_node;
      }

      if ((!cur_node || s_json_get_type(cur_node) == S_JSON_TYPE_NULL) && s[0] == '?')
        return "null";

      return NULL;
    }
#line 3054 "sjson.gen.c"
yy212:
		yyaccept = 5;
		yych = (guchar)*(m = ++c);
		if (yych == 't') goto yy222;
yy213:
#line 1251 "sjson.c"
		{
      CHECK_TYPE(S_JSON_TYPE_STRING)
    }
#line 3064 "sjson.gen.c"
yy214:
		yyaccept = 6;
		yych = (guchar)*(m = ++c);
		if (yych == 'u') goto yy216;
yy215:
#line 1247 "sjson.c"
		{
      CHECK_TYPE(S_JSON_TYPE_NUMBER)
    }
#line 3074 "sjson.gen.c"
yy216:
		yych = (guchar)*++c;
		if (yych == 'm') goto yy218;
yy217:
		c = m;
		if (yyaccept <= 3) {
			if (yyaccept <= 1) {
				if (yyaccept <= 0) {
					goto yy198;
				} else {
					goto yy205;
				}
			} else {
				if (yyaccept <= 2) {
					goto yy207;
				} else {
					goto yy209;
				}
			}
		} else {
			if (yyaccept <= 5) {
				if (yyaccept <= 4) {
					goto yy211;
				} else {
					goto yy213;
				}
			} else {
				goto yy215;
			}
		}
yy218:
		yych = (guchar)*++c;
		if (yych != 'b') goto yy217;
		yych = (guchar)*++c;
		if (yych != 'e') goto yy217;
		yych = (guchar)*++c;
		if (yych != 'r') goto yy217;
		yych = (guchar)*++c;
		goto yy215;
yy222:
		yych = (guchar)*++c;
		if (yych != 'r') goto yy217;
		yych = (guchar)*++c;
		if (yych != 'i') goto yy217;
		yych = (guchar)*++c;
		if (yych != 'n') goto yy217;
		yych = (guchar)*++c;
		if (yych != 'g') goto yy217;
		yych = (guchar)*++c;
		goto yy213;
yy227:
		yych = (guchar)*++c;
		if (yych != 't') goto yy217;
		yych = (guchar)*++c;
		if (yych != 'e') goto yy217;
		yych = (guchar)*++c;
		if (yych != 'g') goto yy217;
		yych = (guchar)*++c;
		if (yych != 'e') goto yy217;
		yych = (guchar)*++c;
		if (yych != 'r') goto yy217;
		yych = (guchar)*++c;
		goto yy211;
yy233:
		yych = (guchar)*++c;
		if (yych != 'o') goto yy217;
		yych = (guchar)*++c;
		if (yych != 'l') goto yy217;
		yych = (guchar)*++c;
		if (yych != 'e') goto yy217;
		yych = (guchar)*++c;
		if (yych != 'a') goto yy217;
		yych = (guchar)*++c;
		if (yych != 'n') goto yy217;
		yych = (guchar)*++c;
		goto yy209;
yy239:
		yych = (guchar)*++c;
		if (yych != 'j') goto yy217;
		yych = (guchar)*++c;
		if (yych != 'e') goto yy217;
		yych = (guchar)*++c;
		if (yych != 'c') goto yy217;
		yych = (guchar)*++c;
		if (yych != 't') goto yy217;
		yych = (guchar)*++c;
		goto yy207;
yy244:
		yych = (guchar)*++c;
		if (yych != 'r') goto yy217;
		yych = (guchar)*++c;
		if (yych != 'a') goto yy217;
		yych = (guchar)*++c;
		if (yych != 'y') goto yy217;
		yych = (guchar)*++c;
		goto yy205;
yy248:
		yych = (guchar)*++c;
		if (yych == ']') goto yy251;
		goto yy217;
yy249:
		++c;
		yych = (guchar)*c;
		if (yych <= '/') goto yy217;
		if (yych <= '9') goto yy249;
		if (yych != ']') goto yy217;
yy251:
		++c;
#line 1234 "sjson.c"
		{
      if (!cur_node || s_json_get_type(cur_node) != S_JSON_TYPE_ARRAY)
        return NULL;

      guint index;
      sscanf(s + 1, "%u", &index);

      cur_node = s_json_get_element(cur_node, index);
      continue;
    }
#line 3194 "sjson.gen.c"
yy253:
		++c;
		yych = (guchar)*c;
		if (yych <= '@') {
			if (yych <= '-') {
				if (yych >= '-') goto yy253;
			} else {
				if (yych <= '/') goto yy255;
				if (yych <= '9') goto yy253;
			}
		} else {
			if (yych <= '_') {
				if (yych <= 'Z') goto yy253;
				if (yych >= '_') goto yy253;
			} else {
				if (yych <= '`') goto yy255;
				if (yych <= 'z') goto yy253;
			}
		}
yy255:
#line 1221 "sjson.c"
		{
      if (!cur_node || s_json_get_type(cur_node) != S_JSON_TYPE_OBJECT)
        return NULL;

      // zero terminate member name on stack
      gchar* name = g_alloca((c - s));
      memcpy(name, s + 1, c - (s + 1));
      name[c - (s + 1)] = '\0';

      cur_node = s_json_get_member(cur_node, name);
      continue;
    }
#line 3228 "sjson.gen.c"
yy256:
		++c;
		yych = (guchar)*c;
yy257:
		if (yych <= '\f') {
			if (yych <= 0x08) goto yy194;
			if (yych <= '\n') goto yy256;
			goto yy194;
		} else {
			if (yych <= '\r') goto yy256;
			if (yych == ' ') goto yy256;
			goto yy194;
		}
	}
#line 1291 "sjson.c"

  }

  return cur_node;
}

gchar* s_json_compact(const gchar* json)
{
  g_return_val_if_fail(json != NULL, NULL);

  GString* str = g_string_sized_new(strlen(json));
  const guchar* c = (const guchar*)json;
  const guchar* m = NULL;
  const guchar* s;
  const gchar* json_end;

  // validate and isolate
  if (!s_json_is_valid_inner(json, &json_end))
    return NULL;

  while (c < (const guchar*)json_end)
  {
    s = c;


#line 3269 "sjson.gen.c"
	{
		guchar yych;
		unsigned int yyaccept = 0;
		yych = (guchar)*c;
		if (yych <= '9') {
			if (yych <= ' ') {
				if (yych <= '\n') {
					if (yych <= 0x00) goto yy272;
					if (yych <= 0x08) goto yy274;
					goto yy270;
				} else {
					if (yych == '\r') goto yy270;
					if (yych <= 0x1F) goto yy274;
					goto yy270;
				}
			} else {
				if (yych <= ',') {
					if (yych == '"') goto yy262;
					if (yych <= '+') goto yy274;
				} else {
					if (yych <= '-') goto yy264;
					if (yych <= '/') goto yy274;
					if (yych <= '0') goto yy265;
					goto yy266;
				}
			}
		} else {
			if (yych <= 'm') {
				if (yych <= '\\') {
					if (yych <= ':') goto yy260;
					if (yych != '[') goto yy274;
				} else {
					if (yych <= ']') goto yy260;
					if (yych == 'f') goto yy268;
					goto yy274;
				}
			} else {
				if (yych <= 'z') {
					if (yych <= 'n') goto yy269;
					if (yych == 't') goto yy267;
					goto yy274;
				} else {
					if (yych == '|') goto yy274;
					if (yych >= '~') goto yy274;
				}
			}
		}
yy260:
		++c;
yy261:
#line 1316 "sjson.c"
		{
      g_string_append_len(str, s, c - s);
      continue;
    }
#line 3325 "sjson.gen.c"
yy262:
		yyaccept = 0;
		yych = (guchar)*(m = ++c);
		if (yych >= 0x01) goto yy297;
yy263:
#line 1329 "sjson.c"
		{
      goto err;
    }
#line 3335 "sjson.gen.c"
yy264:
		yych = (guchar)*++c;
		if (yych <= '/') goto yy263;
		if (yych <= '0') goto yy295;
		if (yych <= '9') goto yy286;
		goto yy263;
yy265:
		yyaccept = 1;
		yych = (guchar)*(m = ++c);
		if (yych <= 'D') {
			if (yych == '.') goto yy288;
			goto yy261;
		} else {
			if (yych <= 'E') goto yy289;
			if (yych == 'e') goto yy289;
			goto yy261;
		}
yy266:
		yyaccept = 1;
		yych = (guchar)*(m = ++c);
		goto yy287;
yy267:
		yyaccept = 0;
		yych = (guchar)*(m = ++c);
		if (yych == 'r') goto yy284;
		goto yy263;
yy268:
		yyaccept = 0;
		yych = (guchar)*(m = ++c);
		if (yych == 'a') goto yy281;
		goto yy263;
yy269:
		yyaccept = 0;
		yych = (guchar)*(m = ++c);
		if (yych == 'u') goto yy277;
		goto yy263;
yy270:
		++c;
		yych = (guchar)*c;
		goto yy276;
yy271:
#line 1321 "sjson.c"
		{
      continue;
    }
#line 3381 "sjson.gen.c"
yy272:
		++c;
#line 1325 "sjson.c"
		{ 
      break;   
    }
#line 3388 "sjson.gen.c"
yy274:
		yych = (guchar)*++c;
		goto yy263;
yy275:
		++c;
		yych = (guchar)*c;
yy276:
		if (yych <= '\f') {
			if (yych <= 0x08) goto yy271;
			if (yych <= '\n') goto yy275;
			goto yy271;
		} else {
			if (yych <= '\r') goto yy275;
			if (yych == ' ') goto yy275;
			goto yy271;
		}
yy277:
		yych = (guchar)*++c;
		if (yych == 'l') goto yy279;
yy278:
		c = m;
		if (yyaccept <= 0) {
			goto yy263;
		} else {
			goto yy261;
		}
yy279:
		yych = (guchar)*++c;
		if (yych != 'l') goto yy278;
yy280:
		yych = (guchar)*++c;
		goto yy261;
yy281:
		yych = (guchar)*++c;
		if (yych != 'l') goto yy278;
		yych = (guchar)*++c;
		if (yych != 's') goto yy278;
		yych = (guchar)*++c;
		if (yych == 'e') goto yy280;
		goto yy278;
yy284:
		yych = (guchar)*++c;
		if (yych != 'u') goto yy278;
		yych = (guchar)*++c;
		if (yych == 'e') goto yy280;
		goto yy278;
yy286:
		yyaccept = 1;
		m = ++c;
		yych = (guchar)*c;
yy287:
		if (yych <= '9') {
			if (yych == '.') goto yy288;
			if (yych <= '/') goto yy261;
			goto yy286;
		} else {
			if (yych <= 'E') {
				if (yych <= 'D') goto yy261;
				goto yy289;
			} else {
				if (yych == 'e') goto yy289;
				goto yy261;
			}
		}
yy288:
		yych = (guchar)*++c;
		if (yych <= '/') goto yy278;
		if (yych <= '9') goto yy293;
		goto yy278;
yy289:
		yych = (guchar)*++c;
		if (yych <= ',') {
			if (yych != '+') goto yy278;
		} else {
			if (yych <= '-') goto yy290;
			if (yych <= '/') goto yy278;
			if (yych <= '9') goto yy291;
			goto yy278;
		}
yy290:
		yych = (guchar)*++c;
		if (yych <= '/') goto yy278;
		if (yych >= ':') goto yy278;
yy291:
		++c;
		yych = (guchar)*c;
		if (yych <= '/') goto yy261;
		if (yych <= '9') goto yy291;
		goto yy261;
yy293:
		yyaccept = 1;
		m = ++c;
		yych = (guchar)*c;
		if (yych <= 'D') {
			if (yych <= '/') goto yy261;
			if (yych <= '9') goto yy293;
			goto yy261;
		} else {
			if (yych <= 'E') goto yy289;
			if (yych == 'e') goto yy289;
			goto yy261;
		}
yy295:
		yyaccept = 1;
		yych = (guchar)*(m = ++c);
		if (yych <= 'D') {
			if (yych == '.') goto yy288;
			goto yy261;
		} else {
			if (yych <= 'E') goto yy289;
			if (yych == 'e') goto yy289;
			goto yy261;
		}
yy296:
		++c;
		yych = (guchar)*c;
yy297:
		if (yych <= '"') {
			if (yych <= 0x00) goto yy278;
			if (yych <= '!') goto yy296;
			goto yy280;
		} else {
			if (yych != '\\') goto yy296;
		}
yy298:
		++c;
		yych = (guchar)*c;
		if (yych <= 'e') {
			if (yych <= '/') {
				if (yych == '"') goto yy300;
				if (yych <= '.') goto yy278;
				goto yy300;
			} else {
				if (yych <= '\\') {
					if (yych <= '[') goto yy278;
					goto yy300;
				} else {
					if (yych == 'b') goto yy300;
					goto yy278;
				}
			}
		} else {
			if (yych <= 'q') {
				if (yych <= 'f') goto yy300;
				if (yych == 'n') goto yy300;
				goto yy278;
			} else {
				if (yych <= 's') {
					if (yych <= 'r') goto yy300;
					goto yy278;
				} else {
					if (yych <= 't') goto yy300;
					if (yych >= 'v') goto yy278;
				}
			}
		}
		++c;
		yych = (guchar)*c;
		if (yych <= '@') {
			if (yych <= '/') goto yy278;
			if (yych <= '9') goto yy302;
			goto yy278;
		} else {
			if (yych <= 'F') goto yy302;
			if (yych <= '`') goto yy278;
			if (yych <= 'f') goto yy302;
			goto yy278;
		}
yy300:
		++c;
		yych = (guchar)*c;
		if (yych <= '"') {
			if (yych <= 0x00) goto yy278;
			if (yych <= '!') goto yy300;
			goto yy280;
		} else {
			if (yych == '\\') goto yy298;
			goto yy300;
		}
yy302:
		++c;
		yych = (guchar)*c;
		if (yych <= '@') {
			if (yych <= '/') goto yy278;
			if (yych >= ':') goto yy278;
		} else {
			if (yych <= 'F') goto yy303;
			if (yych <= '`') goto yy278;
			if (yych >= 'g') goto yy278;
		}
yy303:
		++c;
		yych = (guchar)*c;
		if (yych <= '@') {
			if (yych <= '/') goto yy278;
			if (yych >= ':') goto yy278;
		} else {
			if (yych <= 'F') goto yy304;
			if (yych <= '`') goto yy278;
			if (yych >= 'g') goto yy278;
		}
yy304:
		++c;
		yych = (guchar)*c;
		if (yych <= '@') {
			if (yych <= '/') goto yy278;
			if (yych <= '9') goto yy300;
			goto yy278;
		} else {
			if (yych <= 'F') goto yy300;
			if (yych <= '`') goto yy278;
			if (yych <= 'f') goto yy300;
			goto yy278;
		}
	}
#line 1332 "sjson.c"

  }

  return g_string_free(str, FALSE);

err:
  g_string_free(str, TRUE);
  return NULL;
}
